### ISSUE TITLE
Unable to start when using Docker

### ISSUE THREAD

**Issue by ezzizzle** [ClaperCo/Claper#101]
Hi there. I'm trying to get Claper up and going using Docker. I've used the `docker-compose.yml` file and the `.env.example` file from the repo but keep running into the error below:

```
claper-app-1  | ** (ArgumentError) could not call Module.put_attribute/3 because the module Claper.Repo.Migrations.CreateUsersAuthTables is already compiled
claper-app-1  |     (elixir 1.16.0) lib/module.ex:2360: Module.assert_not_readonly!/2
claper-app-1  |     (elixir 1.16.0) lib/module.ex:2041: Module.__put_attribute__/5
claper-app-1  |     lib/claper-2.1.0/priv/repo/migrations/20211007145520_create_events.exs:2: (module)
```

I've tried with the Docker image for version 2.1.0 and 2.0 and both exhibit the same error after starting. I can get it to run using the 1.7 image. The `.env` file I'm using has the following options set:

```
BASE_URL=http://localhost:4000
DATABASE_URL=postgres://claper:claper@db:5432/claper
SECRET_KEY_BASE=*****
PRESENTATION_STORAGE=local
PRESENTATION_STORAGE_DIR=/app/uploads
MAIL_TRANSPORT=local
MAIL_FROM=noreply@claper.co
MAIL_FROM_NAME=Claper
```

Grateful for any advice of things I may have overlooked.

**Comment by alxlion** [comment]
Hi, 

What is your Docker version ? Can you show the docker compose file ?

Thanks
