### ISSUE TITLE
Feat: Export of form submissions

### ISSUE THREAD

**Issue by janvykopal** [ClaperCo/Claper#103]
Please add an export of answers from forms to CSV or XLS for further processing outside Claper.

**Comment by alxlion** [comment]
You can already export forms answer to csv: https://docs.claper.co/usage/forms.html#export-submissions

**Comment by janvykopal** [comment]
@alxlion I reuse events to have same access codes. I can export answers only after the event has been terminated. Would it be possible to have View report button even for live events?
