### ISSUE TITLE
Error The page is under maintenance, we'll be back soon

### ISSUE THREAD

**Issue by tomcatcw1980** [ClaperCo/Claper#104]
Hello, 

I have installed Claper and successfully designed a survey. This survey also works when I enter the code.

However, as soon as I copy this as a template and then want to enter the copy as, I get the error message that reads something like: “The page is under maintenance, we'll be back soon!”

What is the problem here? I would be glad if you could help.

Regards
Christian

**Comment by alxlion** [comment]
This bug was fixed in the latest release. I let you test it and come back if you still have issues.

**Comment by tomcatcw1980** [comment]
Thanx, now it works. 

Greetings
