### ISSUE TITLE
SECRET_KEY_BASE configuration option is required.

### ISSUE THREAD

**Issue by odonald** [ClaperCo/Claper#106]
Hi there,
First of all, thanks for sharing this project!!! I used docker compose to test it, and it's pretty cool! 

I wanted to start developing some features for this but I'm already getting stuck at the very first steps :D 

I'm following the steps from the docs "[Development Environment](https://docs.claper.co/self-hosting/development.html)" but Step 5 `mix deps.get` produces this error: 
```
Compiling 131 files (.ex)
Generated claper app
** (RuntimeError) SECRET_KEY_BASE configuration option is required. See https://docs.claper.co/configuration.html#production-docker
    /Users/me/Documents/code/playground/Claper/config/runtime.exs:35: (file)
    (stdlib 6.1.1) erl_eval.erl:904: :erl_eval.do_apply/7
    (stdlib 6.1.1) erl_eval.erl:271: :erl_eval.exprs/6
    (elixir 1.17.3) lib/code.ex:572: Code.validated_eval_string/3
    (elixir 1.17.3) lib/config.ex:290: Config.__eval__!/3
```

I'm guessing this is related to the .env file but I have renamed it from .env.sample to .env and updated the secret using `mix phx.gen.secret`

Unfortunately [https://docs.claper.co/configuration.html#production-docker](https://docs.claper.co/configuration.html#production-docker) is not available for me to check.

Feeling a bit nooby at this point, but any idea why I am seeing this? 

I have the required prerequisites mentioned in the docs.

**Comment by alxlion** [comment]
Hello @odonald , thanks for trying to improve Claper 💟  

You can check this documentation: https://docs.claper.co/self-hosting/development.html 

It's recommended to not use Docker when you want to develop on the source code directly, so just follow these steps. If you still have some issues, I will improve the documentation with missing informations if so.
