### ISSUE TITLE
[Feature Request] Show external link support

### ISSUE THREAD

**Issue by IsaacHatton** [ClaperCo/Claper#116]
Hi,

I'd like to send a link to my attendees that they can click on and access in another browser tab, as one of the services I want to embed doesn't support embedding, and another one needs a larger window size than the iframe shown to attendees (even on a iPad screen it appears very small).

Is there a way of doing this I have missed? If not, please could this be added?

I've tried adding a web interacton of an <a> tag but it doesn't let me put raw HTML in, and links sent as messages don't seem to be clickable. 

Slido also offers an option to let the event manager put links in the side menu (where currently Claper only displays a Leave option), which could also work for me.

I'm selfhosting Claper using the docker image, and except for this minor issue I'm really liking the software, thanks for making it!

Many thanks,
Isaac

**Comment by alxlion** [comment]
Yes I will add hyperlink detection on messages

**Comment by alxlion** [comment]
You can now have clickable hyperlinks in messages. It is available in the `dev' release and will be available in the next release.

**Comment by IsaacHatton** [comment]
OK thanks that is amazing, is there a way I can run the dev version in docker?

Is it just a matter of git cloning the dev branch rather than the default one before running docker compose up?

**Comment by alxlion** [comment]
Replace `image: ghcr.io/claperco/claper:latest` with `image: ghcr.io/claperco/claper:dev`

**Comment by IsaacHatton** [comment]
Thanks it is working amazingly!
