### ISSUE TITLE
Talent show Voting system.

### ISSUE THREAD

**Issue by lordbagel42** [ClaperCo/Claper#23]
Basically, allow people to vote a number from 1-10, rating a performer in a talent show or other competition. Then, average all the inputs, making a rating for the performer. Maybe allow a difference of 60-40% weight for judges vs audience, or an adjustable weighting.

**Comment by lordbagel42** [comment]
where was this completed?

**Comment by alxlion** [comment]
It is too specific to be added to the product at the moment
