### ISSUE TITLE
Feat: Hide answers of poll / Quizz

### ISSUE THREAD

**Issue by deployn** [ClaperCo/Claper#25]
Hello, 
I wanted to bring up the idea of adding a feature to hide the current poll results. This would be beneficial for quizzes as it would prevent participants from being influenced by the current voting trends and promote more independent answers.

**Comment by alxlion** [comment]
It could be better to have a quizz feature with a correct answer than a hidden poll.
I keep this issue for this feature ;) 

Thanks

**Comment by eduproinf** [comment]
Hi!
From my point of view, a "Show results on answer" checkbox on poll creation would be very useful.
When using a poll just to check audience opinions there is no "correct answer" as in a quiz, but it anyhow it may be exciting for the people at the event having to wait until the "screen" shows final results. That would be ideal for the usage I would like to give to clapper.
Regards!

**Comment by yatesdr** [comment]
This feature is critical for me, and is preventing me from using Claper today.  I don't want the audience polling to be affected by group-think!   If there is a way to workaround so it's just not showing the results to the audience members at all I'd love it.   In most of the presentations it's important to get unbiased feedback, but if you've got 100 people poll and the first 10 pick a similar answer, it for sure influences the rest of the group when they tend to go with the herd.

**Comment by alxlion** [comment]
Ok I'll add an option to toggle to hide the answers in the next release.

**Comment by alxlion** [comment]
This feature is now available in the `dev` branch, will be available in the next release (v2.0)

https://github.com/ClaperCo/Claper/assets/1835726/68453557-fdb2-44ba-ad00-f76a2f5f6f6d
