### ISSUE TITLE
Bug: 400 Error in Hosted Presentation Mode

### ISSUE THREAD

**Issue by DerekDaffara** [ClaperCo/Claper#26]
Hello!

Within the Hosted version, upon hitting the 'Start' Button to enter Presentation Mode, a 400 Error is returned.

![image](https://user-images.githubusercontent.com/83874963/214174090-6c001713-3998-426c-911d-99e236465ee8.png)

![image](https://user-images.githubusercontent.com/83874963/214173927-f4bf0d11-e3b3-4439-8190-3a34ca699d94.png)

Let me know if any other information is needed.  Thanks!

**Comment by alxlion** [comment]
Thanks for your report! Hosted version has been fixed and also fixed in v1.2.1
