### ISSUE TITLE
[Feature request] Add the possibility to have interaction templates in files uploaded.

### ISSUE THREAD

**Issue by nicolas-graves** [ClaperCo/Claper#29]
Hi Claper!
I'm working in my free time for an environmental organization, and we're considering moving from wooclap to Claper. 
I've just tested the app and it seems great, thanks a lot for the good work (unfortunately, we don't rely on stable financing, so it's difficult to contribute more than a few bucks)! 

Our use case is that we have a template presentation that different people will use to present, with a few slides changing from a presentation to another. 

One feature we miss during the test was the possibility to have a template presentation allowing not to rewrite each interaction for each presentation. The system wooclap had in integration with ggl slides was quite simple : a title and a link as metadata in the comment section. 

If this is possible to do within a pptx file import, it would greatly help us in our future presentations. I can be more precise in a later comment if useful!

**Comment by alxlion** [comment]
Hi !

Thanks for considering Claper.

If I read correctly, you want to import interactions from another presentation, correct?

**Comment by nicolas-graves** [comment]
The functionality we need is to quickly create a presentation with interactions from another very close presentation. 

Yes, the ability to import interactions from another presentation would help us. 

The way I described it in my previous message was in a way to include interactions in metadata of pptx slides, so that writing the right comment on a slide would yield the right interaction for a slide (I don't know however how easy it is to parse comments of a pptx file). 

Both would be helpful for our usecase, thanks for your quick answer!

**Comment by alxlion** [comment]
This could be a good feature, but I think metadata is not the right way to do it. 

I'll probably add an option when you create a presentation to import interaction from another presentation. I add it to the roadmap.

**Comment by alxlion** [comment]
This feature is on v1.4 🎉
