### ISSUE TITLE
[Feature request] Add possibility to manage / present again a presentation

### ISSUE THREAD

**Issue by nicolas-graves** [ClaperCo/Claper#30]
Hi!

Just another note from the testing process. 

I must have put a wrong presentation finish time. I've just finished to prepare my intervention, I now have a "Finished" label on it. 

Would be great to have the option to either represent or copy the presentation totally. 

Thanks again, I hope this is useful feedback.

**Comment by alxlion** [comment]
Nice to have 👍

**Comment by alxlion** [comment]
In the next release (v2.0), presentation doesn't have finish time anymore. It solves this issue.

Available in the `dev` version atm.
