### ISSUE TITLE
[Feature request] Translations management

### ISSUE THREAD

**Issue by Dynnammo** [ClaperCo/Claper#33]
**Context**
As a developer, I would like to have the possibility to use Claper in the language of my audience.

**Solution(s)**
1) Provide an localisation interface (like Weblate or Crowdin) in order for contributors to add their native language and translate Claper
2) If not possible yet, add a section in the README.md (or CONTRIBUTING.md if necessary) explaining how to get started with PO files.

**Comment by alxlion** [comment]
You can contribute to the translations [here](https://poeditor.com/join/project/HbRyvyt3TT).

**Comment by Dynnammo** [comment]
Fast ! Thanks @alxlion , I'm looking at it right now !

**Comment by alxlion** [comment]
Thanks for your contribution 🤝 

Translations are not very clean (some strings contain HTML), I'll clean that in the future but for the moment it's enough to go on.
