### ISSUE TITLE
[Feature request] Videos, poll in slides, correct answer, notes

### ISSUE THREAD

**Issue by matthieu637** [ClaperCo/Claper#34]
Hello,
Very interesting project! Thanks for you work.

Here is a list of features that could be great:
- support for slides with video (maybe with beamer/latex as I'm not sure its doable with raw PDF)
- possibility to directly put the poll in the slides in a text form (like http://www.quizzoodle.com/) 
- possibility to define what was the correct answer of a poll
- possibility to display notes for the speaker (ideally with the beamer option "show notes on second screen")

**Comment by cromulus** [comment]
So... yes, I would also like these.
