### ISSUE TITLE
SMTP is not working

### ISSUE THREAD

**Issue by mariushosting** [ClaperCo/Claper#36]
I have set up Email SMTP but unfortunately it doesn't work.
Tried port 465, port 587 SSL, TLS, everything, unfortunately nothing works.

**Comment by alxlion** [comment]
Hello,

As it is, Claper does not send emails. So it is not necessary to configure the SMTP parameters to make it functional.

**Comment by mariushosting** [comment]
@alxlion Thanks for letting me know. Btw I did not understand why in the documentation there is environment for SMTP. https://docs.claper.co/configuration.html

**Comment by alxlion** [comment]
Indeed, I'm thinking of removing this part from the doc soon. Thanks for the feedback!
