### ISSUE TITLE
Set MAX_FILE_SIZE_MB not reflecting in UI

### ISSUE THREAD

**Issue by t347s** [ClaperCo/Claper#37]
Hi,
I change the variable "MAX_FILE_SIZE_MB" in docker-compose and in frontend that change is not reflected:
![image](https://github.com/ClaperCo/Claper/assets/31503790/df2efddd-b626-44f3-8627-8d132362e930)
![image](https://github.com/ClaperCo/Claper/assets/31503790/a58b7e31-2792-4812-b563-53360b493f69)

Thank you!

**Comment by alxlion** [comment]
Fixed on the `dev` branch: https://github.com/ClaperCo/Claper/commit/d6ee041383d347a47c494eba4a2f2bf76b20aed0

Will be released in v1.4.1
