### ISSUE TITLE
Is there any way a presenter could see the notes from the PPTX?

### ISSUE THREAD

**Issue by SorynZ** [ClaperCo/Claper#45]
We would like to know if there is any way we could inlcude the notes from within the PPTX when uploading the original presentation. These should be then displayed only in the presenters view. 
This will greatly help us in maintaing a coherent presentation.

**Comment by alxlion** [comment]
Sorry, there is no such a feature at the moment.

**Comment by SorynZ** [comment]
Thanks for the feedback! Do you see it as a potential feature in the future? If yes, how long 'till then?

**Comment by alxlion** [comment]
It could be a useful feature, but I don't think it will be implemented in Claper. I'll make a note of the idea and think about it.
Thanks for your feedback
