### ISSUE TITLE
Add docker image for amd64 / fix M1 & Pi error

### ISSUE THREAD

**Issue by jpgreth** [ClaperCo/Claper#46]
I would appreciate it if you could provide a docker image, which is compiled for amd64.
Until now, when running the docker compose on an apple M1 or Raspberry Pi, there is an error `standard_init_linux.go:228: exec user process caused: exec format error`.

This error could be issued by several possibilities. One is the wrong docker image. This could also be issued by wrong script encoding or missing/wrong shebang.

Please take a look and make it runnable on the mentioned platforms.

**Comment by alxlion** [comment]
I'll look into providing an image for amd. For the moment, you can refer to the documentation to get it working: https://docs.claper.co/installation.html#arm-architecture
