### ISSUE TITLE
```ENABLE_ACCOUNT_CREATION=false``` doesn't prevent account creation

### ISSUE THREAD

**Issue by adamdadd** [ClaperCo/Claper#48]
This is possibly known or correct behaviour however I had assumed passing the env  would disable the ability to create an account however it removes the option to create an account from the UI  but allows account creation by navigating to https://example.com/users/register. 

This could be handled by LB or proxy but thought it may be worth clarifying in documentation if this is the correct behavior

**Comment by alxlion** [comment]
Hi @adamdadd , thanks for your feedback. 
It's not a correct behavior, I'll fix this in the next release.

**Comment by alxlion** [comment]
Fixed on 1.6.0
