### ISSUE TITLE
Chat messages should wrap at spaces or hypens

### ISSUE THREAD

**Issue by bpoulliot** [ClaperCo/Claper#53]
I can set this up and provide screenshots and demos, but running this for a few presentations this is one of two issues I ran into.

Expected behavior: chat messages sent will wrap at end of word or hyphenate words when feasible.
Produced behavior: chat messages are wrapped at the character limit for lines, regardless of the location within a word.

**Comment by alxlion** [comment]
Fixed on 1.6.0 (`dev`), thanks for your contribution!
