### ISSUE TITLE
Polls do not scroll on mobile devices

### ISSUE THREAD

**Issue by bpoulliot** [ClaperCo/Claper#54]
Polls that have more than a few (more than 3-4) options on most mobile devices will take up the entire screen. The poll itself appears to be a modal overlay on top of the backdrop of the web app. The modal itself does not allow for scrolling, which means if you have 5+ options, polls cannot be completed on mobile devices.

Expected behavior: longer polls with many (5+ options) allow for scrolling to select later options as well as voting/submission.
Produced behavior: polls with many options display the poll modal with later options off screen, causing both options and voting to be inaccessible.

**Comment by alxlion** [comment]
Fixed on 1.6.0 (`dev`), thanks for your contribution!
