### ISSUE TITLE
Upload files are lost - docker

### ISSUE THREAD

**Issue by ssamjh** [ClaperCo/Claper#55]
I'm noticing that the uploads' folder is not being retained, and in fact nothing is being inserted into the folder.

I've tested this on the main and dev branches.

Docker config

```version: "3.0"
services:
  db:
    image: postgres:9
    ports: 
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: claper
      POSTGRES_USER: claper
      POSTGRES_DB: claper
    volumes:
      - /opt/Claper/db:/var/lib/postgresql/data
  app:
    image: ghcr.io/claperco/claper:dev
    ports: 
      - 4000:4000
    volumes:
      - /opt/Claper/uploads:/app/priv/static/uploads
    environment:
      PRESENTATION_STORAGE: "local"
      DATABASE_URL: postgres://claper:claper@db:5432/claper
      SECRET_KEY_BASE: 0LZiQBLw4WvqPlz4cz8RsHJlxNiSqM9B48y4ChyJ5v1oA0L/TPIqRjQNdPZN3iEG
      MAIL_TRANSPORT: smtp
      ENDPOINT_PORT: 443
      ENDPOINT_HOST: "hidden"
      SMTP_RELAY: "smtp-relay.brevo.com"
      MAIL_FROM_NAME: "hidden"
      SMTP_USERNAME: "hidden"
      SMTP_PASSWORD: "hidden"
      SMTP_PORT: "587"
      SMTP_TLS: "if_available"
    depends_on:
      - db
```

**Comment by bpoulliot** [comment]
I have no idea where I found this, but I had to alter what was in the documentation pretty significantly to find the actual uploads folder to map to:
`"${DOCKER}/claper/uploads:/app/lib/claper-1.4.1/priv/static/uploads"`
This retains uploads.

**Comment by ssamjh** [comment]
I can confirm my uploads are in the `/app/lib/claper-1.6.0/priv/static/uploads` folder also.

**Comment by alxlion** [comment]
Indeed, it sounds pretty confusing. I'll look into it and come up with a simpler solution for storage.

**Comment by alxlion** [comment]
It's fixed on the `dev` branch, you can directly bind upload folder with:
```
volumes:
      - uploads:/app/uploads
```

And your presentation files will not be deleted.

It will be available in the future release.
