### ISSUE TITLE
Update translation in Docker container

### ISSUE THREAD

**Issue by tzwaeaen** [ClaperCo/Claper#57]
Hi,

I updated parts of the German translation on POEditor. Is there some way to update the files in the Docker container to check which ones need to be updated as well?

**Comment by alxlion** [comment]
There is no way to update translations in the Docker image without rebuilding it with the new translations.

The current POEdit workflow is not yet very stable, needs some work to be smooth. Thanks a lot for your contribution, I added your changes to the project!
