### ISSUE TITLE
Inconsistence Translation

### ISSUE THREAD

**Issue by raniaamina** [ClaperCo/Claper#58]
Thanks for this awesome project.

Btw, I found a translation inconsistency on the wait page, the day month and date don't seem to follow the local EN. Or is there a special way to set this part?

If there is an editable translation for Indonesian, I am ready to become a translator.

![gambar](https://github.com/ClaperCo/Claper/assets/22146607/6ebd1ee2-8823-4e0f-aac5-6232ea185648)

**Comment by alxlion** [comment]
Hi! Thanks for your report. I fixed that in the next release (1.6.0)

We are using POEdit for translation collaboration, but we are limited to the number of strings translated, so we cannot add other languages at the moment. 

I'll come back to you if we have another solution.

Thanks for using Claper!
