### ISSUE TITLE
Keyboard Shortcuts

### ISSUE THREAD

**Issue by ubaumann** [ClaperCo/Claper#59]
It would be nice to be able to control the screen settings (show instructions, show messages, show poll results) by keyboard. So the mouse is not needed.

**Comment by alxlion** [comment]
Nice to have !

**Comment by alxlion** [comment]
Here are the shortcuts to implements

![CleanShot 2023-10-20 at 10 47 15](https://github.com/ClaperCo/Claper/assets/1835726/f2da3c32-a7d4-4b4e-98bf-0759cbb01423)

**Comment by prateekkalra** [comment]
@alxlion Is it Q/W/E/A/S+some key(like ctrl) or just Q/W/E/A/S ?

**Comment by alxlion** [comment]
> @alxlion Is it Q/W/E/A/S+some key(like ctrl) or just Q/W/E/A/S ?

Just single keys, no combination with others.

**Comment by prateekkalra** [comment]
@alxlion I tried to setup the project on codespaces. I ran the app using docker. But I wasn't able to create a presentation. Clicking create doesn't do anything. Am I doing something wrong?

**Comment by alxlion** [comment]
Have you any errrors in the console ?

**Comment by alxlion** [comment]
This feature has been merged on `dev` branch and will be available in the next release.
