### ISSUE TITLE
[Feature] Add embed (excalidraw, youtube...)

### ISSUE THREAD

**Issue by alxlion** [ClaperCo/Claper#61]
# Description

Add an "Embed" interaction on a slide like a Youtube video or any website with an `iframe`.

# Specs

You can take inspiration from other interactions like Polls or Forms.

### Presenter

When an embed is enabled and is in the current slide position, show it in full screen.

### Manager

When clicking on "Add interraction", add this option to the popup: 

![CleanShot 2023-10-20 at 11 29 16](https://github.com/ClaperCo/Claper/assets/1835726/edb3b9cd-5b9a-4f3c-8d24-589131ad6e84)

Use this icon: 

```
<svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="w-6 h-6">
  <path stroke-linecap="round" stroke-linejoin="round" d="M14.25 9.75L16.5 12l-2.25 2.25m-4.5 0L7.5 12l2.25-2.25M6 20.25h12A2.25 2.25 0 0020.25 18V6A2.25 2.25 0 0018 3.75H6A2.25 2.25 0 003.75 6v12A2.25 2.25 0 006 20.25z" />
</svg>
```

When selecting "Embed", show a form with fields `title`  and  `content` (get your inspirations from other interactions like Polls and Forms).

The `content` field is a textarea and the user has to fill it with an iframe. (`<iframe></iframe>`)

When added, you can enable it (like any other interactions). Do not forget: By enabling an interaction, you have to disable the others (only one enabled interaction by slide).

### Report (when event is ended)

Display embed, if present, on the current slide in the report.

![CleanShot 2023-10-20 at 11 44 54](https://github.com/ClaperCo/Claper/assets/1835726/eb0ad044-f255-4391-bd11-c33616365983)

## Back

When an Embed is added, broadcast it to all (presenter + manager + attendees). Like I said before, take your inspiration from other interactions like Forms or Polls.

When an Embed is enabled, disable any other interaction on the current slide.

## Database

Add a table `embeds` with columns `title` (string), `content` (string), `position` (int), `presentation_file_id` (int / foreign key), `enabled` (bool), `inserted_at` (timestamp), `updated_at` (timestamp).

**Comment by Usama4745** [comment]
Hey @alxlion can you explain it little bit more what needs to be done?
What I understood is that we need to define iframe somewhere where we can add youtube videos?

**Comment by alxlion** [comment]
@Usama4745 Sorry, I forgot the specs. I edited the first message. I hope it's enough for you, do no hesitate if you have questions and if you have some ideas/improvement to the original specs.

Thanks 🙏

**Comment by Usama4745** [comment]
@alxlion thanks for feedback. I will start working on it
/attempt #61

**Comment by Usama4745** [comment]
facing this error while running 

`mix ecto.migrate`

`** (RuntimeError) SECRET_KEY_BASE configuration option is required. See https://docs.claper.co/configuration.html#production-docker
    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.2) lib/code.ex:656: Code.eval_string_with_error_handling/3
    (elixir 1.12.2) lib/config.ex:258: Config.__eval__!/3
    (elixir 1.12.2) lib/config/reader.ex:86: Config.Reader.read!/2
    (mix 1.12.2) lib/mix/tasks/loadconfig.ex:57: Mix.Tasks.Loadconfig.load_runtime/1
    (mix 1.12.2) lib/mix/tasks/app.config.ex:38: Mix.Tasks.App.Config.run/1`

@alxlion can you confirm where do we need to add SECRET_KEY_BASE variable for this issue

**Comment by alxlion** [comment]
> facing this error while running 
> 
> 
> 
> `mix ecto.migrate`
> 
> 
> 
> `** (RuntimeError) SECRET_KEY_BASE configuration option is required. See https://docs.claper.co/configuration.html#production-docker
> 
>     (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
> 
>     (elixir 1.12.2) lib/code.ex:656: Code.eval_string_with_error_handling/3
> 
>     (elixir 1.12.2) lib/config.ex:258: Config.__eval__!/3
> 
>     (elixir 1.12.2) lib/config/reader.ex:86: Config.Reader.read!/2
> 
>     (mix 1.12.2) lib/mix/tasks/loadconfig.ex:57: Mix.Tasks.Loadconfig.load_runtime/1
> 
>     (mix 1.12.2) lib/mix/tasks/app.config.ex:38: Mix.Tasks.App.Config.run/1`
> 
> 
> 
> @alxlion can you confirm where do we need to add SECRET_KEY_BASE variable for this issue

Yes, it is on the documentation : https://docs.claper.co/configuration.html#production-docker

**Comment by haruncurak** [comment]
Hi @Usama4745 are you still working on this? Happy to help out or take over for this task if you're facing some issues.

**Comment by Usama4745** [comment]
hey @haruncurak I am still not able to setup project. while using docker image getting issue of folder not getting created for presentation file.

**Comment by alxlion** [comment]
> hey @haruncurak I am still not able to setup project. while using docker image getting issue of folder not getting created for presentation file.

Docker is used for deployment, it is not suited for development. It's better to have elixir installed on your computer and a db in Docker for example.

**Comment by Usama4745** [comment]
> > hey @haruncurak I am still not able to setup project. while using docker image getting issue of folder not getting created for presentation file.
> 
> Docker is used for deployment, it is not suited for development. It's better to have elixir installed on your computer and a db in Docker for example.

I was facing multiple issues while installing in my windows system now I have installed WSL and trying on it

**Comment by Usama4745** [comment]
Hey @alxlion I have duplicated .env from .env.sample and added SECRET_KEY_BASE mix phx.gen.secret command but I am still facing this issue while running mix ecto.migrate can you confirm what needs to be done here?

`** (RuntimeError) SECRET_KEY_BASE configuration option is required. See https://docs.claper.co/configuration.html#production-docker
    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
    (elixir 1.12.2) lib/code.ex:656: Code.eval_string_with_error_handling/3
    (elixir 1.12.2) lib/config.ex:258: Config.__eval__!/3
    (elixir 1.12.2) lib/config/reader.ex:86: Config.Reader.read!/2
    (mix 1.12.2) lib/mix/tasks/loadconfig.ex:57: Mix.Tasks.Loadconfig.load_runtime/1
    (mix 1.12.2) lib/mix/tasks/app.config.ex:38: Mix.Tasks.App.Config.run/1`

**Comment by Usama4745** [comment]
> Hey @alxlion I have duplicated .env from .env.sample and added SECRET_KEY_BASE mix phx.gen.secret command but I am still facing this issue while running mix ecto.migrate can you confirm what needs to be done here?
> 
> `** (RuntimeError) SECRET_KEY_BASE configuration option is required. See https://docs.claper.co/configuration.html#production-docker (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6 (elixir 1.12.2) lib/code.ex:656: Code.eval_string_with_error_handling/3 (elixir 1.12.2) lib/config.ex:258: Config.__eval__!/3 (elixir 1.12.2) lib/config/reader.ex:86: Config.Reader.read!/2 (mix 1.12.2) lib/mix/tasks/loadconfig.ex:57: Mix.Tasks.Loadconfig.load_runtime/1 (mix 1.12.2) lib/mix/tasks/app.config.ex:38: Mix.Tasks.App.Config.run/1`

Well I have just resolve the issue by adding correct value for secret key inside config/runtime.exs file

**Comment by alxlion** [comment]
Merged ! Will be on the next release.
