### ISSUE TITLE
[Feature] Show/Hide Reactions

### ISSUE THREAD

**Issue by joleaf** [ClaperCo/Claper#66]
Hey, sometimes, I do not want to see the "Reactions" in my presentation. So an admin toggle button to enable/disable this feature (like "show messages", etc...) would be great.

<img src='https://github.com/ClaperCo/Claper/assets/71190322/9b3aa630-9c38-4e3d-9f48-16dad10b87e7' width='200'>

This button should show/hide the "Like", "Dislike", "Clap", and "Heart" reaction buttons from the audiance chat.

**Comment by joleaf** [comment]
@alxlion Is it possible to reopen this issue? I think that in a more formal environment the reactions popping up from the bottom may not be appropriate for such a setting..

**Comment by alxlion** [comment]
The toggle now hides/shows global reactions along with message reactions. It's deployed on the `dev` branch and will on the next release (2.0.1).
