### ISSUE TITLE
[Feature] Mark question as "answered"

### ISSUE THREAD

**Issue by joleaf** [ClaperCo/Claper#70]
If the comment section is used for questions by the audience, the moderator may mark questions as "answered".

Maybe make it fuzzy based on the final question mark at the end of the sentence of the "comment"?

![image](https://github.com/ClaperCo/Claper/assets/71190322/3de67677-ab3a-431d-aa88-2d66804ad0ac)

**Comment by alxlion** [comment]
This use case can be achieved with the new "pinned" message feature #42
