### ISSUE TITLE
[Feature] Add translation documentation for people wanting to help translating

### ISSUE THREAD

**Issue by Dynnammo** [ClaperCo/Claper#75]
## Context
As a user, I would like to help translating Claper

## Frustration
~No documentation whatsoever about it in the README~
Current documentation is about developing, we should complete it with translation documentation.

## Solution
Provide a CONTRIBUTING.md file with all contribution possibilities (development, translation, sponsoring, etc.)

**Comment by alxlion** [comment]
Yes, we had to stop using poeditor.com because it's too limited and the integration with the project is not so smooth. So I'll document the translation process using the PO files soon.

**Comment by Dynnammo** [comment]
> Yes, we had to stop using poeditor.com because it's too limited and the integration with the project is not so smooth. So I'll document the translation process using the PO files soon.

I think Crowdin or Weblate are battle-tested solutions (which I use for other projects).
If help needed I may help.

**Comment by eduproinf** [comment]
I would like to help with translation, so looking foward to hearing from this HOWTO about the translation process

**Comment by alxlion** [comment]
The translation process is now explained in the [`CONTRIBUTING.md`](https://github.com/ClaperCo/Claper/blob/dev/CONTRIBUTING.md#translations) on the `dev` branch.
