### ISSUE TITLE
quarto presentations?

### ISSUE THREAD

**Issue by ignacio82** [ClaperCo/Claper#78]
First, thanks for the great work and for making it opensource. 

Is there any hope that you might add support for [quarto presentations](https://quarto.org/docs/presentations/) . My guess is that all it would require is adding some claper code into quarto to embed the relevant survey as an iframe, but i could be wrong.

**Comment by alxlion** [comment]
It will be tricky to implement as Claper is written in Elixir. What's more, it seems to me to be very niche in the scientific community, so I don't think it belongs in Claper, which is intended to be accessible to as many people as possible.

**Comment by progecon** [comment]
Hi @alxlion , just my two cents on this. I can testify that quarto-revealjs presentations are being actively used in both the scientific community (we might have different experiences according to the scientific fields in question) as well as in policy debates. Enabling Quarto to add surveys as iframes would make Claper a killer-alternative in this setting.

**Comment by progecon** [comment]
any response from the dev? Is this a feature that is planned to be integrated at some point?

**Comment by alxlion** [comment]
We have other priorities at the moment, but the community can still contribute.
