### ISSUE TITLE
Feat:  Set the aspect ratio of the presentation window when going to present

### ISSUE THREAD

**Issue by yatesdr** [ClaperCo/Claper#82]
When using with presentation software (OBS, ProPresenter), it would be really nice to have it open a window of defined size and aspect ratio when you click "present".

Couldn't figure out myself how this window is being called or defined, but it should be a pretty straight-forward fix to pop it up in 1920x1080 or something like that.   Will continue looking and try to find a workaround.

**Comment by alxlion** [comment]
It is not specific to Claper, presentation view is adapted to the window size. If you want to change your window size, you can take a look at tools like [Sizer](https://www.brianapps.net/sizer/)
