### ISSUE TITLE
Missing Q&A feature

### ISSUE THREAD

**Issue by dennisorlando** [ClaperCo/Claper#86]
Hi, this project states in different places that it's a solution for Q&A with your audience, but it actually doesn't have such a dedicated feature.
You would need to use the comments section to collect answers and use the :+1: reaction to measure the most requested answers, but there's no "voting" system as SliDo has.

A simple "sort by thumbs up" option would be a neat compromise; a dedicated Q&A interaction feature, with a voting system and the option to sort votes, would be amazing.

**Comment by alxlion** [comment]
Hi @dennisorlando , you might be a bit confused when using Claper after Slido. Claper tends to be more "discussion oriented" and questions are part of that discussion. It's not another Slido.
If someone is dedicated to managing the presentation and moderating, they can "pin" important messages like questions to highlight. But if you're presenting alone, this can be a challenge, even more so at a large event with lots of messages. 

I'm thinking of an automatic question highlighting feature. It will automatically pin questions from your audience based on the number of votes (1 thumbs up = 1 vote). For participants, this should be transparent, it's not another pop-up window or section for asking questions, they stay in the current discussion space. For you, just look at the pinned message in the dashboard to check the best questions to answer, without filtering or effort.

I'm going to experiment with this solution to see if it's a good idea.

It's essential to have real feedback on your use case to evolve.

Thanks for your report.

**Comment by alxlion** [comment]
This is a preview of the questions section. It detects questions from messages, and you can filter and sort them by likes.

This is available in the `dev` branch and Docker image.

https://github.com/ClaperCo/Claper/assets/1835726/d277862c-9fc6-40dc-aa56-4dded5a75bd9
