### ISSUE TITLE
Quiz feature

### ISSUE THREAD

**Issue by zagub59** [ClaperCo/Claper#93]
Hey there,
I'm trying out Claper right now and I can't find a way to create an interactive quizz. 
Is this possible at this moment ? 
What I would like to do is create a quizz with correct answers (hidden to the viewers) and a point calculation system to show up who gave the most right answers at the end of the quizz.
Thanks !

**Comment by alxlion** [comment]
You can create a poll and hide answers already, but there is no "gamification" feature with correct answers and points. This is a something lot of people want, so I added it to the roadmap.

**Comment by zagub59** [comment]
Hi @alxlion, 
Thank you for adding it to the roadmap (and sorry for the late answer!).

**Comment by alxlion** [comment]
Quizzes are now available in the v2.3.0
