### ISSUE TITLE
Question: Admin user?

### ISSUE THREAD

**Issue by joleaf** [ClaperCo/Claper#94]
Hi!
I saw that there exists an admin user: https://github.com/ClaperCo/Claper/blob/main/priv/repo/seeds.exs
What is the password for this user? And can this user manage other users? I wonder why there is the option to disable the registration (`ENABLE_ACCOUNT_CREATION=true`) if there is no admin user, which can add new users in some kind of backend?
Thank you!

**Comment by alxlion** [comment]
There is no default user, seed is not valid anymore. You can create a first account and then disable the account creation.
