### ISSUE TITLE
[Feature request] Allow reusing Events

### ISSUE THREAD

**Issue by Robot8A** [ClaperCo/Claper#96]
Some use cases may require reusing the same material multiple times as different events.
Any of these could work:
- Allow export and re-upload the event including all polls, forms and embedded content.
- Allow duplicating an event
- Allow resetting/reopening an already finished event

We consider #30 partially implements this, but reusing an already opened event does not reset the results.
As a use case, I want to organize a similar event/lecture on multiple dates with different audiences.

**Comment by alxlion** [comment]
Thanks for your feedback, you can import all the interactions from another event when you click on "Add interaction" in your freshly created event. 
An option to duplicate the event completely with the presentation file could be good 👍

**Comment by alxlion** [comment]
You can now duplicate events.
