### ISSUE TITLE
[Feature request] Multiple questions in one poll.

### ISSUE THREAD

**Issue by luisvalenzuelar** [ClaperCo/Claper#98]
Hey there, I love Claper. It's very intuitive, clean and user friendly. I just miss more functionality. Say you want to make a quiz with more than one question in a given slide. You need to create two separate quizzes, and manually activate them. Other apps allow for full flexibility of number of questions, with the ability to choose if participants can move freely among them or are paced by the presenter. 

Also, the separation between polls and forms is not necessary. You could create questions that mix both types, again, with allowing for more than one question. In the end, forms is rather a different type of question (open). The fact that has an email field is irrelevant. 

My use case is university teaching rather than "events" and the suggested flexibility would greatly enhance its use in my field (like also #96).

**Comment by alxlion** [comment]
Hello,

Regarding your first question about the quiz, there is no quiz feature at the moment, only polls. It's on the roadmap (#93). Polls are always paced by the moderator.

Polls and forms are two different features. Polls are predefined answers that users have to choose between. Forms are often used to collect user information or specific requests that can be exported to a CSV after the event. This is neither a quiz nor a poll. 

I think you're talking about the quiz feature in your whole request, again it's an upcoming feature and not available yet.
